// Generated types for Supabase database
// This will be auto-generated by Supabase CLI later, but defining manually for now

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          uvec_calendar_url: string | null
          google_refresh_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          uvec_calendar_url?: string | null
          google_refresh_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          uvec_calendar_url?: string | null
          google_refresh_token?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          user_id: string
          source: 'uvec' | 'gclassroom'
          source_id: string
          name: string
          color: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          source: 'uvec' | 'gclassroom'
          source_id: string
          name: string
          color?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          source?: 'uvec' | 'gclassroom'
          source_id?: string
          name?: string
          color?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          user_id: string
          course_id: string | null
          source: 'uvec' | 'gclassroom' | 'manual'
          source_id: string | null
          title: string
          description: string | null
          due_date: string | null
          max_score: number | null
          status: 'not_started' | 'in_progress' | 'done'
          priority: 'urgent_important' | 'important' | 'urgent' | 'neither' | null
          submission_state: string | null
          created_at: string
          updated_at: string
          synced_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course_id?: string | null
          source: 'uvec' | 'gclassroom' | 'manual'
          source_id?: string | null
          title: string
          description?: string | null
          due_date?: string | null
          max_score?: number | null
          status?: 'not_started' | 'in_progress' | 'done'
          priority?: 'urgent_important' | 'important' | 'urgent' | 'neither' | null
          submission_state?: string | null
          created_at?: string
          updated_at?: string
          synced_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string | null
          source?: 'uvec' | 'gclassroom' | 'manual'
          source_id?: string | null
          title?: string
          description?: string | null
          due_date?: string | null
          max_score?: number | null
          status?: 'not_started' | 'in_progress' | 'done'
          priority?: 'urgent_important' | 'important' | 'urgent' | 'neither' | null
          submission_state?: string | null
          created_at?: string
          updated_at?: string
          synced_at?: string
        }
      }
      sync_logs: {
        Row: {
          id: string
          user_id: string
          source: 'uvec' | 'gclassroom'
          status: 'success' | 'failed'
          tasks_added: number | null
          tasks_updated: number | null
          error_message: string | null
          synced_at: string
        }
        Insert: {
          id?: string
          user_id: string
          source: 'uvec' | 'gclassroom'
          status: 'success' | 'failed'
          tasks_added?: number | null
          tasks_updated?: number | null
          error_message?: string | null
          synced_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          source?: 'uvec' | 'gclassroom'
          status?: 'success' | 'failed'
          tasks_added?: number | null
          tasks_updated?: number | null
          error_message?: string | null
          synced_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_tasks_due_today: {
        Args: {
          user_uuid: string
        }
        Returns: {
          id: string
          title: string
          course_name: string
          source: string
          due_date: string
        }[]
      }
      get_overdue_tasks: {
        Args: {
          user_uuid: string
        }
        Returns: {
          id: string
          title: string
          course_name: string
          source: string
          due_date: string
          days_overdue: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}